tasks:
  - name: Setup Chromium
    before: pip install -r requirements.txt
    init: pytest --browser chromium
  - name: Setup Firefox
    before: pip install -r requirements.txt
    init: pytest --browser firefox